name: Build & Publish Java Connector

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-maybe-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java/connector

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Needed for GitVersion to see history

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
          build-root-directory: java/connector

      # --- GitVersion ---
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '5.x'

      - name: Compute version with GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3

      - name: Echo version
        run: |
          echo "semVer=${{ steps.gitversion.outputs.semVer }}"
          echo "informational=${{ steps.gitversion.outputs.informationalVersion }}"

      # Create & push tag if this isn't a tag build
      - name: Create tag if needed
        id: maybe_tag
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          TAG="v${{ steps.gitversion.outputs.semVer }}"
          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
            echo "did_tag=true" >> $GITHUB_OUTPUT
          else
            echo "did_tag=false" >> $GITHUB_OUTPUT
          fi
        working-directory: .  # tagging at repo root

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build
        env:
          VERSION: ${{ steps.gitversion.outputs.semVer }}
        run: ./gradlew clean build -Pversion="${VERSION}"

      - name: Test
        run: ./gradlew test

      # Publish only when building a tag (either pushed or just created above)
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/tags/') || steps.maybe_tag.outputs.did_tag == 'true' }}
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.gitversion.outputs.semVer }}
        run: ./gradlew publish -Pversion="${VERSION}"
