name: Release Discord Bot

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Manual trigger
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build Discord Bot
        run: |
          cd discordbot
          go build -o rotaria-bot

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: discordbot/rotaria-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}