name: Release

on:
    push:
        tags:
            - 'v*'
        paths:
         - '.github/workflows/release.yml'



jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build
              uses: ./github/workflows/go-build
            - name: Create release
              uses: actions/create-release@v1.1.4
              env: 
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                tag_name: ${{github.ref_name}}
                release_name: ${{github.ref_name}}
                draft: false
                prerelease: false